apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jmeter-cronjob
  labels:
    app: jmeter-cronjob
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: jmeter-cronjob
        spec:
          volumes:
            - name: volume-1
              persistentVolumeClaim:
                claimName: testing-jmeter
          containers:
            - name: jmeter-cronjob
              image: 'juankanh/jmeter-docker:latest'
              command: ["bash","info.sh"]
              resources: {}
              volumeMounts:
                - name: volume-1
                  mountPath: /result
          restartPolicy: Never
status: {}