apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jmeter-cronjob
spec:
  schedule: "2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: jmeter
        spec:
          volumes:
            - name: volume-1
              persistentVolumeClaim:
                claimName: testing-jmeter
          containers:
            - name: test-jmeter
              image: 'juankanh/jmeter-docker:latest'
              command: [ "jmeter","-p","custom.properties","-n","-t","testing.jmx" ]
              resources: {}
              volumeMounts:
                - name: volume-1
                  mountPath: /result
          restartPolicy: Never