apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-job
spec:
  template:
    metadata:
      labels:
        app: jmeter
    spec:
      volumes:
        - name: volume-1
          persistentVolumeClaim:
            claimName: testing-jmeter
      containers:
        - name: test-jmeter
          image: 'juankanh/jmeter-docker:latest'
          command: ["bash","info.sh"]
          resources: {}
          volumeMounts:
            - name: volume-1
              mountPath: /result
      restartPolicy: Never