kind: Job
apiVersion: batch/v1
metadata:
  name: jmeter-job
  creationTimestamp: null
  labels:
    app: jmeter-cronjob
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jmeter-job
    spec:
      volumes:
        - name: volume-1
          persistentVolumeClaim:
            claimName: testing-jmeter
        - name: volume-2
          configMap:
            name: jmeter-run
      containers:
        - name: jmeter-job
          image: 'juankanh/jmeter-docker:latest'
          command: ["bash"]
          args: ["main/info.sh","| /sh"]
          env:
            - name: jmeter-run
              valueFrom:
                configMapKeyRef:
                  name: jmeter-run
                  key: info.sh
          resources: {}
          volumeMounts:
            - name: volume-1
              mountPath: /result
            - name: volume-2
              mountPath: /main
      restartPolicy: Never
status: {}
