kind: Pod
apiVersion: v1
metadata:
  name: test-jmeter
  creationTimestamp: null
  labels:
    app: test-jmeter
spec:
  volumes:
    - name: volume-1
      persistentVolumeClaim:
        claimName: testing-jmeter
  containers:
    - name: test-jmeter
      image: 'juankanh/jmeter-docker:latest'
      command: ["bash","main/info.sh"]
      resources: {}
      volumeMounts:
        - name: volume-1
          mountPath: /result
status: {}
