kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testing-jmeter
  creationTimestamp: null
  labels:
    app: testing-jmeter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
